config/routes.rb
Rails.application.routes.draw do
  get 'users/:id/reviews/new', to: 'reviews#new', as: 'new_user_review'
  post 'users/:id/reviews', to: 'reviews#create', as: 'reviews'
  devise_for :users
  root to: 'pages#home'
  get '/events/new', to: 'events#new', as: 'new_event'
  get '/events/:id', to: 'events#show', as: 'event'
  get '/events', to: 'events#index', as: 'events'
  post '/events', to: 'events#create'
  get '/events/:id/bookings/new', to: 'bookings#new', as: 'new_event_bookings'
  post '/events/:id/bookings', to: 'bookings#create', as: 'event_bookings'
  get '/dashboard', to: 'dashboards#show', as: 'dashboard'
  get '/users/:id', to: 'users#show', as: 'profile'
  patch '/bookings/:id', to: 'bookings#update', as: 'booking'
  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class BookingValidator < ActiveModel::Validator
  def validate(record)
    if record.event.user == record.user
      record.errors[:user] << "Host cannot book his or her own event"
    end
  end
end

class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :event

  enum status: { pending: 0, approved: 1, declined: 2 }
  enum spoon: { "No preference" => 0, "Little Spoon" => 1, "Middle Spoon" => 2,  "Big Spoon" => 3 }


  validates_with BookingValidator
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  validates :title, presence: true
  validates :location, presence: true
  validates :time, presence: true
  validates :max_guest, presence: true
  validates :description, presence: true

  enum host_spoon: { "No preference" => 0, "Little Spoon" => 1, "Middle Spoon" => 2,  "Big Spoon" => 3 }
  include PgSearch::Model
  pg_search_scope :search_by_title_and_description,
    against: [ :title, :description, :host_spoon, :location ],
    associated_against: {
      user: :username
    },
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reviewer, class_name: "User"
  belongs_to :reviewee, class_name: "User"

  validates :rating, inclusion: { in: (0..5).to_a, message: "Rating has to be between 0 to 5" }
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :events, through: :bookings
  has_many :events_as_host, class_name: 'Event'
  has_one_attached :photo
  has_many :reviews_from_guests, class_name: 'Review', foreign_key: :reviewee_id
  has_many :reviews_as_a_guest, class_name: 'Review', foreign_key: :reviewer_id

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end
  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @event = Event.find(params[:id])
    @booking = Booking.new()
    authorize @booking
  end

  def create
    @event = Event.find(params[:id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.event = @event
    authorize @booking
    if @booking.save
      redirect_to event_path(@event)
    else
      render 'new'
    end
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.status = booking_params[:status]
    authorize @booking
    if @booking.save
      redirect_to dashboard_path
    else
      redirect_to events_path
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:spoon, :status)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @events_as_host = current_user.events_as_host
    @bookings = current_user.bookings
    authorize @events_as_host
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def new
    @event = Event.new
    authorize @event
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    authorize @event
    if @event.save
      redirect_to events_path
    else
      render 'new'
    end
  end

  def index
    if params[:query].present?
      @events = Event.search_by_title_and_description(params[:query])
    else
      @events = Event.all
    end
    @markers = @events.geocoded.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { event: event }),
        image_url: helpers.asset_url('noun_hug_146406.svg')
      }
    end
    @events = policy_scope(@events)
  end

  def show
    @event = Event.find(params[:id])
    @user = @event.user
    authorize @event
  end

  private

  def event_params
    params.require(:event).permit(:title, :location, :time, :max_guest, :host_spoon, :description, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @events = Event.last(6)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_user, only: [:show, :new, :create ]
  def new
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @review.reviewee = @user
    @review.reviewer = current_user
    authorize @review
    if @review.save
      redirect_to profile_path(@user)
    else
      render 'new'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy ]
  def show
    @reviews_from_guests = @user.reviews_from_guests
    authorize @user
  end
  def edit
    authorize @user
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
    authorize @user
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:first_name, :last_name, :bio, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="form-card">
  <h2>Book for the nappy</h2>
  <%= simple_form_for([@event, @booking], url: event_bookings_path(@event)) do |f| %>
  <%= f.input :spoon,
  as: :radio_buttons,
  collection: [['no preference', 'No preference'], ['small spoon', 'Little Spoon'], ['middle spoon', 'Middle Spoon'], ['big spoon', 'Big Spoon']],
  label: 'Preferred position',
  class: "radio-label" %>
  <div class="submit-button-wrap">
    <%= f.submit class: "btn btn-light" %>
  </div>
  <% end %>
</div>

app/views/dashboards/show.html.erb
<div class="container min-height">
  <ul class="nav tabs-underlined mt-2" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <a class="active tab-underlined" id="home-tab" data-toggle="tab" href="#bookings" role="tab" aria-controls="home" aria-selected="true">Hosting Events</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="tab-underlined" id="profile-tab" data-toggle="tab" href="#requests" role="tab" aria-controls="profile" aria-selected="false">Events You Booked</a>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade py-3 show active" id="bookings" role="tabpanel" aria-labelledby="home-tab">
      <h1>Events You Are Hosting</h1>
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">#</th>
              <th scope="col">Title</th>
              <th scope="col">Location</th>
              <th scope="col">Time</th>
              <th scope="col">Number of requests</th>
            </tr>
          </thead>
          <tbody>
            <% @events_as_host.each_with_index do |event, index| %>
              <tr class="accordion-toggle collapsed" id="accordion<%= index %>" data-toggle="collapse" data-parent="#accordion<%= index %>" href="#collapse<%= index %>">
                <td class="expand-button"></td>
                <td scope="row"><%= index + 1 %></td>
                <td><%= event.title %></td>
                <td><%= event.location %></td>
                <td><%= event.time.strftime("%a %Y/%m/%d %H:%M") %></td>
                <td><%= event.bookings.count %></td>
              </tr>
              <tr class="hide-table-padding">
                <td></td>
                <td colspan="6">
                  <div id="collapse<%= index %>" class="collapse in p-2 border-bottom">
                    <div class="row">
                      <div class="col-2 font-weight-bold">Username</div>
                      <div class="col-6 font-weight-bold">Preferred Position</div>
                    </div>
                  </div>
                  <% event.bookings.each do |booking| %>
                    <div id="collapse<%= index %>" class="collapse in p-2 border-bottom">
                      <div class="row">
                        <%= link_to profile_path(booking.user), class: "col-2" do %>
                          <div class="col-2" style="color: black"><%= booking.user.username %></div>
                        <% end %>
                        <div class="col-6"><%= booking.spoon %></div>
                        <% if booking.status == "pending" %>
                          <%= simple_form_for booking, remote: true do |f| %>
                            <%= f.input :status, as: :hidden, input_html: { value: 'approved'} %>
                            <%= f.submit 'Accept', class: 'btn btn-primary mr-3' %>
                          <% end %>
                          <%= simple_form_for booking, remote: true do |f| %>
                            <%= f.input :status, as: :hidden, input_html: { value: 'declined'} %>
                            <%= f.submit 'Decline', class: 'btn btn-danger' %>
                          <% end %>
                        <% elsif booking.status == "declined" %>
                          <p class="p-2">Declined</p>
                        <% else %>
                          <p class="p-2">Approved</p>
                        <% end %>
                      </div>
                    </div>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="tab-pane fade py-3" id="requests" role="tabpanel" aria-labelledby="profile-tab">
      <h1>Events You Booked</h1>
      <table class="table table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Location</th>
            <th scope="col">Time</th>
            <th scope="col">Booking Status</th>
          </tr>
        </thead>
        <tbody>
          <!-- if the event is over and declined, it should not show up in the booking -->
          <!-- if the event is over and approved but havent reviewd, it should link a new review -->
          <!-- if the event is over and approved and reviewd, should not show up in the booking -->
          <!-- if the event is not over and approved should just show the booking with the status -->
          <!-- if the event is not over and pending should just show the booking with the status -->
          <% @bookings.each_with_index do |booking, index| %>
            <tr>
              <td scope="row"><%= index + 1 %></td>
              <!-- <#%= link_to new_event_path do %> -->
              <td><%= booking.event.title %></td>
              <!-- <#% end %> -->
              <td><%= booking.event.location %></td>
              <td><%= booking.event.time.strftime("%a %Y/%m/%d %H:%M") %></td>
              <% if booking.status == 'approved' && booking.event.time <= Time.now %>
                <td><%= link_to "Write a review", new_user_review_path(booking.event.user) %></td>
              <% else %>
                <td><%= booking.status %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/events/_card.html.erb
<div class="card card-index-sm" style="">
  <%= link_to " ", event_path(event), class: 'img-link' %>
  <% if event.photo.attached? %>
    <%= cl_image_tag event.photo.key, class: "img" %>
  <% else %>
    <img class="img" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
  <% end %>
  <div class="card-body position-relative p-0">
    <h3><%= event.title %></h3>
    <p>Event starts <em><%= event.time.strftime('%m/%d/%Y %H:%M') %></em></p>
    <p class="card-text"><%= event.description.slice(0..75) %>...</p>
    <% if event.user.photo.attached? %>
      <%= cl_image_tag event.user.photo.key, class: 'avatar-card avatar' %>
    <% else %>
      <img class="avatar-card avatar" src="https://ketteringhealth.org/mediaroom/files/art-of-napping.png" class="card-trip-user avatar-bordered" />
    <% end %>
  </div>
</div>

app/views/events/_info_window.html.erb
<div class="card card-index-sm-no-box-shadow" style="">
  <%= link_to " ", event_path(event), class: 'img-link' %>
  <% if event.photo.attached? %>
    <%= cl_image_tag event.photo.key, class: "img" %>
  <% else %>
    <img class="img" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
  <% end %>
  <div class="card-body position-relative p-0">
    <h3><strong><%= event.title %></strong></h3>
    <p>at <%= event.time.strftime('%m/%d/%Y %H:%M') %></p>
    <p class="card-text"><%= event.description.slice(0..50) %>...</p>
    <% if event.user.photo.attached? %>
      <%= cl_image_tag event.user.photo.key, class: 'avatar-card avatar' %>
    <% else %>
      <img class="avatar-card avatar" src="https://ketteringhealth.org/mediaroom/files/art-of-napping.png" class="card-trip-user avatar-bordered" />
    <% end %>
  </div>
</div>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<div class="container-fluid">
  <div class="row justify-content-around mx-3">
    <div class="col-6">
      <div class='my-2'>
        <%= render 'shared/search_form', width: 75 %>
      </div>
      <div class="cards-index-columns">
        <% @events.each do |event| %>
          <%= render 'events/card', event: event %>
        <% end %>
      </div>
      </div>
      <div class="col-5">
        <div id="map"
          style="width: 100%; height: 88vh;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
</div>

app/views/events/new.html.erb
<div class="form-card">
  <%= simple_form_for @event do |f| %>
      <%= f.input :title %>
      <%= f.input :description, hint: "Describe where you are going to take a nap, what kind of buddy you're looking for, what kind of expectations you have, etc" %>
      <%= f.input :location %>
      <%= f.input :time %>
      <%= f.input :max_guest, label: 'Maximum number of guests', collection: (1..10) %>
      <%= f.input :host_spoon,
                  label: "You're preferred position",
                  as: :radio_buttons,
                  collection: [['no preference', 'No preference'], ['small spoon', 'Little Spoon'], ['middle spoon', 'Middle Spoon'], ['big spoon', 'Big Spoon']],
                  hint: "Imagine literal spoons!" %>
      <%= f.input :photo, as: :file, hint: "Upload photos of the place you're hosting the nap!" %>
      <div class="submit-button-wrap">
        <%= f.submit %>
      </div>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="container min-height-90vh">
  <div class="card-description card-description-img">
    <% if @event.photo.attached? %>
      <%= cl_image_tag @event.photo.key, class: "img-card" %>
    <% else %>
      <img src="https://source.unsplash.com/1100x300/?sleep,nap", class="img-card" alt="event picture">
    <% end %>
  </div>
  <div class="card card-description card-description-left">
    <% if policy(@event).book? %>
      <%= link_to "Book this event ", new_event_bookings_path(@event), class: 'btn btn-success' %>
    <% end %>
    <div class="card-body card-description-text-show">
      <h1 class="title-show"><%= @event.title %></h1>
      <p><span class="h5 font-weight-bold">Description: </span class="h5"></p>
      <p><%= @event.description %></p>
      <p><i class="fas fa-map-marked-alt icon"></i> <%= @event.location %></p>
      <p> <i class="far fa-calendar-alt icon"></i> <%= @event.time.strftime("%A %Y/%m/%d %H:%M") %></p>
      <p><i class="fas fa-users icon"></i> <%= @event.max_guest %></p>
      <p><i class="fas fa-id-badge icon"></i> <%= link_to profile_path(@user) do %>
          <%= @user.username&.capitalize %>
        <% end %>
        <p><i class="far fa-envelope icon"></i> <%= @user.email %> </p>
        <p><i class="fas fa-utensil-spoon icon"></i><%= @event.host_spoon %> </p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Napbuddies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
    <%= yield %>
  <%= render 'shared/flashes' %>
  <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/_header.html.erb
<div class="banner mb-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://ketteringhealth.org/mediaroom/files/art-of-napping.png);">
  <div class="container">
    <h1>Welcome to <strong>Napbuddies</strong>!</h1>
    <p>Never feel <strong>Alone</strong>...</p>
    <%= render 'shared/search_form', width: 50 %>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'pages/header' %>

<div class="container">
  <h3>RECENT EVENTS</h3>
  <div class="cards-index-columns">
    <% @events.each do |event| %>
      <%= render 'events/card', event: event %>
    <% end %>
  </div>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<div class="form-card">
  <h2>write a review for <em><%= @user.username %></em></h2>
  <%= simple_form_for @review do |f| %>
  <%= f.input :content, label: 'Review' %>
  <div class="star-rating">
    <% 5.times do |i| %>
    <input type="radio" name="review[rating]" value="<%= i + 1 %>" <%= "checked" if i == 2 %> />
    <% end %>
  </div>
  <div class="submit-button-wrap mt-5">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This website does not take any responsibility for actions made by users during a nappy <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to events_path, class: "navbar-brand d-flex align-items-center" do %>
    <%= image_tag "noun_hug_146406.svg" %>
    <div id="typewriter">
      <p>Never <strong>FEEL ALONE</strong>...</p>
    </div>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%= link_to "New event", new_event_path, class: "btn btn-success btn-sm mx-3" %>
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, width: 200, height: 200, crop: :fill, gravity: :face,  class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "napbaby.webp", alt: "nap baby", class: "avatar dropdown-toggle", style: "object-fit: cover", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", profile_path(current_user), class: "dropdown-item" %>
            <%= link_to "Events", events_path, class: "dropdown-item" %>
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item"  %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search_form.html.erb
<%= form_tag events_path, method: :get, class: 'form-inline' do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control w-#{width}",
    placeholder: "Preferred nap?"
  %>
  <%= submit_tag "Search", class: "btn btn-info btn-border" %>
<% end %>

app/views/users/edit.html.erb
<%= simple_form_for @user do |f|%>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :bio %>
  <%= f.input :photo, as: :file %>
  <%= f.submit  %>
<% end %>
<%= link_to "change password", edit_user_registration_path(@user), class: "" %>
<%= link_to "Cancel my account", registration_path(@user), data: { confirm: "Are you sure?" }, method: :delete, class: "" %>

app/views/users/show.html.erb
<div class="container">
  <div class="main-body">
    <div class="row">
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body-profile">
            <div class="d-flex flex-column align-items-center text-center">
              <% if @user.photo.attached? %>
                <%= cl_image_tag @user.photo.key, width: 200, height: 200, crop: :fill, gravity: :face, class: "rounded-profile" %>
              <% else %>
                <%= image_tag "napbaby.webp", alt: "nap baby", style: "object-fit: cover", class: "rounded-profile" %>
              <% end %>
              <div class="mt-3">
                <h4> <%= @user.username %> </h4>
                <% if @user == current_user %>
                  <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-primary m-3" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <div class="card mb-3 details-profile">
          <div class="card-body-profile">
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">First Name  </h6>
              </div>
              <div class="col-sm-9">
                <%= @user.first_name %>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Last Name</h6>
              </div>
              <div class="col-sm-9">
                <%= @user.last_name %>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Email</h6>
              </div>
              <div class="col-sm-9">
                <%= @user.email %>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Bio</h6>
              </div>
              <div class="col-sm-9">
                <%= @user.bio %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card p-3">
      <h5 class="card-title">Reviews:</h5>
      <div class="card-body">
        <% @reviews_from_guests.each do |review| %>
          <div class="d-flex justify-content-between">
            <p class="card-text">"<%= review.content %>"</p>
            <div>
              <% review.rating.times do %>
                <i class="fas fa-star"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>